### ISSUE TITLE
Checklist for Status Label

### ISSUE THREAD

**Issue by zbhujwala** [ZBoylan/3DPrinterUI#10]
Errors/Status progress will be caught and updated into the "Status Bar" label

## Statuses to account for:
- [x] Incorrect file type chosen (non-STL file type)
- [x] Implement status label
- [x] Printer not connected (can be generalized down to "Connection error")
- [x] G-code generation status (Working, Complete, Incomplete/Error)
- [x] Printer status (Working, Complete, Incomplete/Error, Paused, Stopped)
- [ ] Errors for Render (unsure about specifics, Rendering team is still working on their parts)
-There may be other errors/statuses that I missed, please add them on to this issue so we can all work on it and keep it in mind.
- [ ] Push our final code to the class repo by Saturday

**Comment by peralta013** [comment]
Incorrect file type chosen (non-STL file type)

- Please review my Error Pop Up Window pull request.

**Comment by ZBoylan** [comment]
Steve mentioned we can use the serial.list()
// Serial.list()   // this will populate an array of strings of the ports on the user computer
https://processing.org/reference/libraries/serial/Serial_list_.html

**Comment by ZBoylan** [comment]
Seems like we don't have variables declared for xArea, yArea and zArea outside of the function which sets them.

" println("x: " + xArea + ", y: " + yArea + ", z: " + zArea); "

**Comment by ZBoylan** [comment]
![screen shot 2017-12-01 at 6 09 07 pm](https://user-images.githubusercontent.com/21044603/33507461-ddc3d934-d6c2-11e7-95e3-15511c0bd18f.png)
Seems like the file name gets chopped off

**Comment by ZBoylan** [comment]
"The createGraphics() function should almost never be used inside draw() because of the memory and time needed to set up the graphics. One-time or occasional use during draw() are acceptable, but code that calls createGraphics() at 60 frames per second will run out of memory or freeze your sketch."
https://processing.org/reference/createGraphics_.html

Line 88 we do this

**Comment by GeorgeVentura** [comment]
yea, none of this code should be in draw()

```java
if (confirmedClicked){
     rendering = createGraphics(250, 250, P3D);  //size of render

    vis = new RenderControler(100,100,100);
    vis.ResetCamera();
    STLParser parser = new STLParser(STLFile);
    ArrayList<Facet> data = parser.parseSTL();
    /*test = new Model(data, .1, .1);
    test.Slice();      // Create gcode in Model object
    gcode = test.getGCode();  
```

**Comment by ZBoylan** [comment]
![screen shot 2017-12-01 at 9 09 28 pm](https://user-images.githubusercontent.com/21044603/33510613-0575314e-d6dc-11e7-8576-8dfa8ffb9125.png)
A way to redirect console output. Need to get it into our Console window. 

appendText() works but new line character doesn't seem to work with GTextField.

**Comment by ZBoylan** [comment]
![screen shot 2017-12-01 at 9 52 23 pm](https://user-images.githubusercontent.com/21044603/33511166-2a78aa4a-d6e4-11e7-80f4-ea6dcbe90f5e.png)
Console window is good 

Now need status label

**Comment by ZBoylan** [comment]
@GeorgeVentura 
           rendering = createGraphics(250, 250, P3D);  //size of render  // P3D
Should we stick that into the confirm file button event handler?

My laptop fan goes full speed and battery drops like crazy when running the UI. I wonder if it has to do with having createGraphics() in draw()?

**Comment by GeorgeVentura** [comment]
> rendering = createGraphics(250, 250, P3D); //size of render // P3D
Should we stick that into the confirm file button event handler?

yea

**Comment by zbhujwala** [comment]
It looks like our status label has attended to the original checklist I posted up here with the exception of Rendering (not sure when Rendering team will be done nor do I know if they throw exceptions/errors to be caught so).

Should we close this issue and focus on documentation/testing now?

**Comment by ZBoylan** [comment]
Yeah, let's close it.
